### ISSUE TITLE
下载完ida64打不开

### ISSUE THREAD

**Issue by sandymandyvip** [swfangzhang/IDA-pro-7-for-Catalina-OSX-15#1]
显示：应用程序“ida64”无法打开。

**Comment by swfangzhang** [comment]
[该链接](https://juejin.im/post/5e019620f265da33c14d2294#heading-3)给出了一个比较好的解决办法，实际情况就是：因每个人环境而异，部分人确实会出现这种情况。

**Comment by YaoJuan** [comment]
直接拖入application之后就打不开了，里面也没有ida 和ida64

**Comment by swfangzhang** [comment]
已更新README，其中给出了最好的解决方案
